update github action
from https://github.com/marketplace/actions/automated-build-android-app-with-github-action

use app because that is our folder structure

Run ./gradlew z959:bundleRelease
  ./gradlew z959:bundleRelease
  shell: /usr/bin/bash -e {0}
  env:
    main_project_module: z959
    playstore_name: z959
    date_today: 2024-08-02
    repository_name: z959
    JAVA_HOME: /opt/hostedtoolcache/Java_Zulu_jdk/17.0.12-7/x64
    JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Zulu_jdk/17.0.12-7/x64
FAILURE: Build failed with an exception.
* What went wrong:
Cannot locate tasks that match 'z959:bundleRelease' as project 'z959' not found in root project 'For ZTE Z959'.
* Try:
> Run gradlew projects to get a list of available projects.
> For more on name expansion, please refer to https://docs.gradle.org/8.7/userguide/command_line_interface.html#sec:name_abbreviation in the Gradle documentation.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
For more on this, please refer to https://docs.gradle.org/8.7/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
BUILD FAILED in 834ms
Error: Process completed with exit code 1.